site_name: Data Science CookBook

nav:
  - Welcome: index.md
  - How-to guides: how-to-guides.md
  - reference.md
  - Unit tests: unit-tests.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Montserrat  # Roboto Mono
  icon:
      repo: fontawesome/brands/github
  logo: assets/elia-group-logo.png
  features:
    - search.suggest
    - navigation.instant
    - content.code.copy

plugins:
  search:
  mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/tomasurdiales/datasciencecookbook
repo_name: GitHub/DataScienceCookBook

copyright: Copyright &copy; 2024 <a href="https://www.eliagroup.eu/">Elia Group</a>. Correspondence to <a href="mailto:tomas.urdialesbartolome@externel.be">tomas.urdialesbartolome@externel.be</a>.
