site_name: mkdocs!

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
      repo: fontawesome/brands/github

  features:
    - search.suggest

plugins:
  - mkdocstrings
  - search

nav:
  - Welcome: index.md
  - tutorials.md
  - How-to guides: how-to-guides.md
  - reference.md
  - explanation.md

repo_url: https://github.com/tomasurdiales/mkdocz
repo_name: GitHub/mkdocz
