site_name: docs!

nav:
  - Welcome: index.md
  - tutorials.md
  - How-to guides: how-to-guides.md
  - reference.md
  - explanation.md
  - Unit tests: unit-tests.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Montserrat  # Roboto Mono
  icon:
      repo: fontawesome/brands/github
  logo: assets/elia-group-logo.png
  features:
    - search.suggest
    - navigation.instant

plugins:
  - mkdocstrings
  - search
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition

repo_url: https://github.com/tomasurdiales/mkdocz
repo_name: GitHub/mkdocz

copyright: Copyright &copy; 2024 <a href="https://www.eliagroup.eu/">Elia Group</a>. Correspondence to <a href="mailto:tomas.urdialesbartolome@externel.be">tomas.urdialesbartolome@externel.be</a>.
